language: python
python:
  - "3.6"

sudo: required
services:
  - docker

before_install:
  - docker pull tbenst/eye-candy
  - docker pull redis
  - git pull https://github.com/tbenst/eye-candy.git
  - cd eye-candy && docker-compose up -d


install:
  - pip install .
  - pip install -r requirements.txt

before_script:

# command to run tests
script: make test
