language: python
python:
  - "3.6"

sudo: required
services:
  - docker

before_install:
  - cd .. && git clone https://github.com/tbenst/eye-candy.git
  - cd eye-candy && docker-compose up -d
  - cd ../glia


install:
  - >
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda env create
  - source activate test
  # - pip install .
  - pip install -r requirements.txt
  - python setup.py install

before_script:

# command to run tests
script: make test
